name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v3

      - name: Instalando o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalando dependências
        run: npm install

      - name: Rodando os testes
        run: npm test

      - name: Build do projeto
        run: npm run 
